
#include <linux/module.h>
#include <linux/platform_device.h>
#include <linux/io.h>
#include <linux/interrupt.h>
#include <linux/delay.h>
#include <linux/kernel.h>
#include <linux/slab.h>
#include <linux/clk.h>
#include <linux/regulator/consumer.h>
#include <linux/of.h>
#include <linux/err.h>
#include <linux/iio/iio.h>
#include <linux/iio/machine.h>
#include <linux/iio/driver.h>

/* Registers based on S3C2416 PDF */
#define S3C2410_ADCCON		0x00
#define S3C2410_ADCTSC		0x04
#define S3C2410_ADCDLY		0x08
#define S3C2410_ADCDAT0		0x0C
#define S3C2410_ADCDAT1		0x10
#define S3C2410_ADCUPDN		0x14
#define S3C2416_ADCMUX		0x18  /* Specific to S3C2416/S3C2443/S5P */

/* ADCCON Bits */
#define S3C2410_ADCCON_ECFLG		BIT(15)
#define S3C2410_ADCCON_PRSCEN		BIT(14)
#define S3C2410_ADCCON_PRSCVL(x)	(((x) & 0xFF) << 6)
#define S3C2416_ADCCON_RESSEL		BIT(3)  /* 0=10bit, 1=12bit */
#define S3C2410_ADCCON_STDBM		BIT(2)
#define S3C2410_ADCCON_READ_START	BIT(1)
#define S3C2410_ADCCON_ENABLE_START	BIT(0)

/* ADCTSC Bits */
#define S3C2410_ADCTSC_XY_PST(x)	(((x) & 0x3) << 0)
#define S3C2410_ADCTSC_AUTO_PST		BIT(2)
#define S3C2410_ADCTSC_PULL_UP_DISABLE	BIT(3)

/* Constants */
#define S3C_ADC_TIMEOUT		msecs_to_jiffies(100)
#define S3C2416_MAX_CHANNELS	10

struct s3c_adc_drvdata {
	bool has_mux_reg;
	int resolution_bit;
};

struct s3c_adc {
	void __iomem *regs;
	struct clk *clk;
	struct regulator *vdd;
	struct completion completion;
	struct mutex lock;
	unsigned int prescale;
};

static void s3c_adc_init_hw(struct s3c_adc *adc)
{
	u32 con;

	/* 
	 * Setup Prescaler
	 * PDF Example: PCLK=50MHz, Prescaler=49 => ADC Freq = 1MHz
	 * Conversion time = 5us
	 */
	con = S3C2410_ADCCON_PRSCEN | S3C2410_ADCCON_PRSCVL(49);
	
	/* Enable 12-bit resolution for S3C2416 */
	con |= S3C2416_ADCCON_RESSEL;
	
	writel(con, adc->regs + S3C2410_ADCCON);
}

static int s3c_adc_read_raw(struct iio_dev *indio_dev,
			    struct iio_chan_spec const *chan,
			    int *val, int *val2, long mask)
{
	struct s3c_adc *adc = iio_priv(indio_dev);
	u32 con, tsc;
	int ret;

	if (mask != IIO_CHAN_INFO_RAW)
		return -EINVAL;

	mutex_lock(&adc->lock);

	reinit_completion(&adc->completion);

	/* 1. Select Channel */
	/* S3C2416 uses specific ADCMUX register for channel selection */
	writel(chan->channel & 0x0F, adc->regs + S3C2416_ADCMUX);

	/* 2. Setup Touchscreen Control to Normal Conversion Mode */
	/* XY_PST = 0, AUTO_PST = 0 */
	tsc = readl(adc->regs + S3C2410_ADCTSC);
	tsc &= ~(S3C2410_ADCTSC_XY_PST(3) | S3C2410_ADCTSC_AUTO_PST);
	writel(tsc, adc->regs + S3C2410_ADCTSC);

	/* 3. Start Conversion */
	con = readl(adc->regs + S3C2410_ADCCON);
	con |= S3C2410_ADCCON_ENABLE_START;
	writel(con, adc->regs + S3C2410_ADCCON);

	/* 4. Wait for IRQ */
	ret = wait_for_completion_timeout(&adc->completion, S3C_ADC_TIMEOUT);
	if (ret == 0) {
		dev_err(&indio_dev->dev, "ADC conversion timed out\n");
		mutex_unlock(&adc->lock);
		return -ETIMEDOUT;
	}

	/* 5. Read Data */
	*val = readl(adc->regs + S3C2410_ADCDAT0) & 0xFFF; /* 12-bit mask */
	
	mutex_unlock(&adc->lock);

	return IIO_VAL_INT;
}

static irqreturn_t s3c_adc_irq_handler(int irq, void *priv)
{
	struct s3c_adc *adc = priv;

	/* 
	 * S3C2416 does not strictly require clearing an INT bit in the ADC block
	 * for pure ADC operations (interrupt is generated by logic), 
	 * but we must ensure we read the data to clear the state in some modes.
	 * The completion signals the read_raw function to proceed.
	 */
	complete(&adc->completion);

	return IRQ_HANDLED;
}

static const struct iio_info s3c_adc_info = {
	.read_raw = s3c_adc_read_raw,
};

/* Define channels 0 to 9 */
#define S3C_ADC_CHAN(_index) {			\
	.type = IIO_VOLTAGE,			\
	.indexed = 1,				\
	.channel = _index,			\
	.info_mask_separate = BIT(IIO_CHAN_INFO_RAW), \
}

static const struct iio_chan_spec s3c_adc_channels[] = {
	S3C_ADC_CHAN(0), S3C_ADC_CHAN(1), S3C_ADC_CHAN(2), S3C_ADC_CHAN(3),
	S3C_ADC_CHAN(4), S3C_ADC_CHAN(5), S3C_ADC_CHAN(6), S3C_ADC_CHAN(7),
	S3C_ADC_CHAN(8), S3C_ADC_CHAN(9),
};

static int s3c_adc_suspend(struct device *dev)
{
	struct iio_dev *indio_dev = dev_get_drvdata(dev);
	struct s3c_adc *adc = iio_priv(indio_dev);
	u32 con;

	/* 
	 * 1. Set ADC to Standby Mode 
	 * This ensures the analog circuitry is powered down safely before we cut the clock.
	 */
	mutex_lock(&adc->lock);
	con = readl(adc->regs + S3C2410_ADCCON);
	con |= S3C2410_ADCCON_STDBM;
	writel(con, adc->regs + S3C2410_ADCCON);
	mutex_unlock(&adc->lock);

	/* 2. Disable Clock to save dynamic power */
	clk_disable_unprepare(adc->clk);

	/* 3. Disable Regulator to save static power (leakage) */
	regulator_disable(adc->vdd);

	return 0;
}

static int s3c_adc_resume(struct device *dev)
{
	struct iio_dev *indio_dev = dev_get_drvdata(dev);
	struct s3c_adc *adc = iio_priv(indio_dev);
	int ret;

	/* 1. Re-enable Regulator */
	ret = regulator_enable(adc->vdd);
	if (ret)
		return ret;

	/* 2. Re-enable Clock */
	ret = clk_prepare_enable(adc->clk);
	if (ret) {
		regulator_disable(adc->vdd);
		return ret;
	}

	/* 
	 * 3. Restore Hardware Configuration 
	 * The registers (Prescaler, Resolution bit) are likely lost/reset.
	 * We reuse the init function to re-apply 12-bit mode and timing.
	 */
	s3c_adc_init_hw(adc);

	return 0;
}

/* Define the PM Operations container */
static const struct dev_pm_ops s3c_adc_pm_ops = {
	.suspend = s3c_adc_suspend,
	.resume  = s3c_adc_resume,
};

static int s3c_adc_probe(struct platform_device *pdev)
{
	struct device *dev = &pdev->dev;
	struct iio_dev *indio_dev;
	struct s3c_adc *adc;
	int ret, irq;

	indio_dev = devm_iio_device_alloc(dev, sizeof(*adc));
	if (!indio_dev)
		return -ENOMEM;

	adc = iio_priv(indio_dev);
	mutex_init(&adc->lock);
	init_completion(&adc->completion);

	/* Map Registers */
	adc->regs = devm_platform_ioremap_resource(pdev, 0);
	if (IS_ERR(adc->regs))
		return PTR_ERR(adc->regs);

	/* Get Interrupt */
	irq = platform_get_irq(pdev, 0);
	if (irq < 0)
		return irq;

	ret = devm_request_irq(dev, irq, s3c_adc_irq_handler, 
			       0, dev_name(dev), adc);
	if (ret)
		return ret;

	/* Get Clock */
	adc->clk = devm_clk_get(dev, "adc");
	if (IS_ERR(adc->clk))
		return dev_err_probe(dev, PTR_ERR(adc->clk), "failed to get clock\n");

	/* Get Regulator */
	adc->vdd = devm_regulator_get(dev, "vdd");
	if (IS_ERR(adc->vdd))
		return dev_err_probe(dev, PTR_ERR(adc->vdd), "failed to get vdd\n");

	/* Enable Resources */
	ret = regulator_enable(adc->vdd);
	if (ret)
		return ret;

	ret = clk_prepare_enable(adc->clk);
	if (ret)
		goto err_regulator;

	s3c_adc_init_hw(adc);

	/* Setup IIO Device */
	indio_dev->name = "s3c2416-adc";
	indio_dev->info = &s3c_adc_info;
	indio_dev->modes = INDIO_DIRECT_MODE;
	indio_dev->channels = s3c_adc_channels;
	indio_dev->num_channels = ARRAY_SIZE(s3c_adc_channels);

	ret = iio_device_register(indio_dev);
	if (ret)
		goto err_clk;

	platform_set_drvdata(pdev, indio_dev);
	dev_info(dev, "S3C ADC driver registered\n");

	return 0;

err_clk:
	clk_disable_unprepare(adc->clk);
err_regulator:
	regulator_disable(adc->vdd);
	return ret;
}

static int s3c_adc_remove(struct platform_device *pdev)
{
	struct iio_dev *indio_dev = platform_get_drvdata(pdev);
	struct s3c_adc *adc = iio_priv(indio_dev);

	iio_device_unregister(indio_dev);
	clk_disable_unprepare(adc->clk);
	regulator_disable(adc->vdd);

	return 0;
}

static const struct of_device_id s3c_adc_dt_ids[] = {
	{ .compatible = "samsung,s3c2416-adc" },
	{ /* sentinel */ }
};
MODULE_DEVICE_TABLE(of, s3c_adc_dt_ids);

static struct platform_driver s3c_adc_driver = {
	.probe = s3c_adc_probe,
	.remove = s3c_adc_remove,
	.driver = {
		.name = "s3c2416-adc",
		.of_match_table = s3c_adc_dt_ids,
		.pm = &s3c_adc_pm_ops,
	},
};

module_platform_driver(s3c_adc_driver);